services:
  - type: web
    name: nf-ai-dados
    runtime: docker
    dockerfilePath: ./Dockerfile.backend
    plan: free
    healthCheckPath: /
    envVars:
      - key: FLASK_APP
        value: app.py
      - key: FLASK_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: nf-ai-postgres
          property: connectionString
      - key: GEMINI_API_KEY
        sync: false

databases:
  - name: nf-ai-postgres
    plan: free
    databaseName: nf_ai
    user: postgres
    postgresMajorVersion: 15

